version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppass}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminpass}
    ports:
      - "5050:80"
    depends_on:
      - db
  backend:
    build: ./backend
    command: bash -c "python scripts/migrate.py && uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT}:5173"
    command: npm run dev -- --host
    depends_on:
      - backend
volumes:
  db_data:
