name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: appdb
          POSTGRES_USER: appuser
          POSTGRES_PASSWORD: apppass
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U appuser -d appdb" \
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Migrate (idempotency check)
        env:
          DATABASE_URL: postgresql+psycopg://appuser:apppass@localhost:5432/appdb
        run: |
          python backend/scripts/migrate.py
          python backend/scripts/migrate.py

      - name: Backend tests
        env:
          DATABASE_URL: postgresql+psycopg://appuser:apppass@localhost:5432/appdb
          JWT_SECRET: ci-secret
          ALLOWED_ORIGINS: http://localhost:5173
          ENV: test
        run: |
          pytest -q

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend deps & tests
        run: |
          cd frontend
          npm ci
          npm test --silent
